import Toy from "../assets/toys.jpg";

export const ToysList = [
  {
    id: 1,
    name: "Pink Rabbit",
    type: "Build-a-Bear",
    age: 2,
    gender: "Female",
    category: "Stuffed Toys",
    image: Toy,
    quantity: 3,
    xyz: "Toys",
  },
  {
    id: 2,
    name: "Red Car",
    type: "Porsche Car",
    age: 3,
    gender: " Male",
    category: "Cars",
    image: Toy,
    quantity: 3,
    xyz: "Toys",
  },
  {
    id: 3,
    name: "Monopoly",
    type: "Monopoly Deal",
    age: 7,
    gender: "Female",
    category: "Board Games",
    image: Toy,
    quantity: 3,
    xyz: "Toys",
  },
  {
    id: 4,
    name: "Barbie",
    type: "Dua Lipa",
    age: 5,
    gender: "Female",
    category: "Dolls",
    image: Toy,
    quantity: 3,
    xyz: "Toys",
  },
  {
    id: 5,
    name: "Football",
    type: "Black and White",
    age: 10,
    gender: "Male",
    category: "Sports",
    image: Toy,
    quantity: 3,
    xyz: "Toys",
  },
  {
    id: 6,
    name: "Jump Rope",
    type: "Elastic",
    age: 12,
    gender: "Male",
    category: "Outdoor",
    image: Toy,
    quantity: 3,
    xyz: "Toys",
  },
];
